# Tokenización

In [2]:
!pip install -U scikit-learn

In [3]:
import pandas as pd

In [4]:
df= pd.read_csv('df_total.csv', encoding='UTF-8')
df

url  \
0      https://www.larepublica.co/redirect/post/3201905   
1      https://www.larepublica.co/redirect/post/3210288   
2      https://www.larepublica.co/redirect/post/3240676   
3      https://www.larepublica.co/redirect/post/3342889   
4      https://www.larepublica.co/redirect/post/3427208   
...                                                 ...   
1212  https://www.bbva.com/es/como-lograr-que-los-in...   
1213  https://www.bbva.com/es/podcast-como-nos-afect...   
1214   https://www.larepublica.co/redirect/post/3253735   
1215  https://www.bbva.com/es/bbva-y-barcelona-healt...   
1216   https://www.larepublica.co/redirect/post/3263980   

                                                   news           Type  
0     Durante el foro La banca articulador empresari...           Otra  
1     El regulador de valores de China dijo el domin...   Regulaciones  
2     En una industria históricamente masculina como...       Alianzas  
3     Con el dato de marzo el IPC interanual encaden...  Macroeconomia  
4     Ayer en Cartagena se dio inicio a la versión n...           Otra  
...                                                 ...            ...  
1212  En la vida de toda empresa emergente llega un ...     Innovacion  
1213  La espiral alcista de los precios continúa y g...  Macroeconomia  
1214  Las grandes derrotas nacionales son experienci...       Alianzas  
1215  BBVA ha alcanzado un acuerdo de colaboración c...     Innovacion  
1216  Casi entrando a la parte final de noviembre la...       Alianzas  

[1217 rows x 3 columns]

In [5]:
df['news'][3]

'Con el dato de marzo el IPC interanual encadena su decimoquinta tasa positiva consecutiva. La inflación publicada por el INE se ha mantenido igual respecto al avance del 30 de marzo y se sitúa 22 puntos por encima del dato de febrero que ascendió al 76.De esos 22 puntos de diferencia la mayor parte la colocó el grupo de la vivienda 09 puntos por la subida de la electricidad y el del transporte 07 puntos por el alza de los carburantes. También impulsaron el IPC de marzo el aumento de los precios de la restauración y los servicios de alojamiento y al encarecimiento generalizado de los alimentos especialmente del pescado y el marisco de la carne de las legumbres y hortalizas y de la leche el queso y los huevos.Sin tener en cuenta la rebaja del impuesto especial sobre la electricidad y las variaciones sobre otros impuestos el IPC interanual alcanzó en marzo 107 nueve décimas más que la tasa general del 98. Así lo refleja el IPC a impuestos constantes que el INE también publica en el marco

In [6]:
# Vamos a separara los datos en variables de entrada y etiquetas
X= df['news']
y= df['Type']


In [7]:
# Vamos a mostrar que en la variable y estamos guardando los valores de las etiquetas y cuantos hay de cada uno 
print(df['Type'].value_counts())

Type
Macroeconomia     340
Alianzas          247
Innovacion        195
Regulaciones      142
Sostenibilidad    137
Otra              130
Reputacion         26
Name: count, dtype: int64


In [8]:
# Vamos a importar la libreria que nos va a permitir dividir el conjunto en entrenamiento y test del modelo
from sklearn.model_selection import train_test_split


In [9]:
# Ponemos para que nos arroje los valores en x(entrenamiento) x(prueba) y lo mismo para las "y"
# le podemos especificar el tamaño del conjunto de test y se elige entre 0.2 a 0.35 es cuestion del usuario
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)


In [10]:
X_train

365     He sido muy crítico de la política exterior no...
864     Netflix Inc. puede descubrir pronto cuántos de...
512     Según un estudio desarrollado por The Martec G...
462     Todos los esfuerzos de América Latina para red...
143     Las acciones subieron y los rendimientos de lo...
                              ...                        
991     Las finanzas descentralizadas, o DeFi, pueden ...
783     Carlos Serrano Herrera economista jefe de BBVA...
1086    Con miras a enfrentar el efecto del cambio cli...
1082    La inflación del Reino Unido se aceleró más de...
645     En el marco de Andicom Microsoft desarrolla un...
Name: news, Length: 912, dtype: object

In [11]:
X_test

646     La industria publicitaria es un nicho que nunc...
681     Airbnb Inc dijo el jueves que extenderá una pr...
285     BBVA Open Innovation busca apoyar la transform...
1092    Los precios al por mayor de Japón aumentaron 9...
1197    BBVA continúa ampliando los servicios, herrami...
                              ...                        
1121    La empresa de alimentos Alpina y la de café Ju...
481     BBVA ha obtenido la nota más alta entre los ba...
300     BBVA participó de Forbes Revolución Fintech Su...
1058    Banco de Bogotá y Habi se unieron para iniciar...
118     Ayer la Alianza del Pacífico conformada por Co...
Name: news, Length: 305, dtype: object

In [12]:
y_train

365           Alianzas
864       Regulaciones
512         Reputacion
462     Sostenibilidad
143      Macroeconomia
             ...      
991         Innovacion
783      Macroeconomia
1086          Alianzas
1082     Macroeconomia
645           Alianzas
Name: Type, Length: 912, dtype: object

In [13]:
y_test

646       Regulaciones
681       Regulaciones
285         Innovacion
1092     Macroeconomia
1197        Innovacion
             ...      
1121          Alianzas
481     Sostenibilidad
300         Innovacion
1058          Alianzas
118           Alianzas
Name: Type, Length: 305, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer


In [15]:
vectorizer= CountVectorizer()

In [33]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

In [35]:
X_test_transformed


<305x25903 sparse matrix of type '<class 'numpy.int64'>'
	with 67055 stored elements in Compressed Sparse Row format>

In [37]:
# Vectorizamos los datos y los mostramos 
X_train_transformed_dense= X_train_transformed.toarray()
print(X_train_transformed_dense)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [39]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [45]:
# Este modelo tiene alrededor del 75-80%
model = MultinomialNB()
model.fit(X_train_transformed, y_train)
y_pred = model.predict(X_test_transformed)
print(metrics.accuracy_score(y_test,y_pred))

# Tokenización simple apartirr del conteo

0.7770491803278688


# Stemming

In [48]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

In [50]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\oscar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\oscar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [52]:
stemmer= SnowballStemmer('spanish')

In [58]:
# Vamos a crear una función donde haya una tokenización del texto pasado a minusculas a cada unos de esos tokens le vamos
# a aplicar el stemmer luego lo vamos a unir para que quede en la frase o en la noticia pero ahora stemmeada
def tokenize_and_stem(text):
    tokens = word_tokenize(text.lower())
    stems = [stemmer.stem(token) for token in tokens if token.isalpha()]
    return ' '.join(stems)

In [60]:
df['news_stemmer'] = df['news'].apply(tokenize_and_stem)

In [61]:
df['news_stemmer']

0       durant el for la banc articul empresarial par ...
1       el regul de valor de chin dij el doming que bu...
2       en una industri histor masculin com lo es la a...
3       con el dat de marz el ipc interanual encaden s...
4       ayer en cartagen se dio inici a la version num...
                              ...                        
1212    en la vid de tod empres emergent lleg un momen...
1213    la espiral alcist de los preci continu y gener...
1214    las grand derrot nacional son experient trauma...
1215    bbva ha alcanz un acuerd de colabor con barcel...
1216    casi entrand a la part final de noviembr la ep...
Name: news_stemmer, Length: 1217, dtype: object

In [64]:
print(df['news_stemmer'][3])

con el dat de marz el ipc interanual encaden su decimoquint tas posit consecut la inflacion public por el ine se ha manten igual respect al avanc del de marz y se situ punt por encim del dat de febrer que ascend al esos punt de diferent la mayor part la coloc el grup de la viviend punt por la sub de la electr y el del transport punt por el alza de los carbur tambien impuls el ipc de marz el aument de los preci de la restaur y los servici de aloj y al encarec generaliz de los aliment especial del pesc y el marisc de la carn de las legumbr y hortaliz y de la lech el ques y los ten en cuent la rebaj del impuest especial sobr la electr y las variacion sobr otros impuest el ipc interanual alcanz en marz nuev decim mas que la tas general del asi lo reflej el ipc a impuest constant que el ine tambien public en el marc de esta inflacion subyacent sin aliment no elabor ni product energet aument en marz cuatr decim hast su valor mas alto desd septiembr de de este mod la subyacent se situ mas de 

In [70]:
# Separamos los datos en variables de entrada y etiquetas
X= df['news_stemmer']
y= df['Type']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)
vectorizer = CountVectorizer()
X_train_transformed= vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_transformed, y_train)

# Medimos el rendimiento swl modelo
y_pred = model.predict(X_test_transformed)

print(metrics.accuracy_score(y_test,y_pred))

# Este modelo nos da un poco más de eficacia que el anterior

0.8426229508196721


In [72]:
X_train_transformed

<912x11694 sparse matrix of type '<class 'numpy.int64'>'
	with 186398 stored elements in Compressed Sparse Row format>

# Lemmatization

In [75]:
import spacy

In [77]:
nlp= spacy.load('es_core_news_sm')

In [81]:
# Crear una función donde le entregaremos los textos pero primero paandolos a minusculas y luego lemmatizandolos
# Y nos regresara el texto pero ya lematizada

def lemmatize_text(text):
    doc = nlp(text.lower())
    lemmas = [token.lemma_ for token in doc if token.is_alpha]
    return ' '.join(lemmas)

In [83]:
df['news_lemma'] = df['news'].apply(lemmatize_text)

In [85]:
df['news_lemma']

0       durante el foro el banca articulador empresari...
1       el regulador de valor de china decir el doming...
2       en uno industria históricamente masculino como...
3       con el dato de marzo el ipc interanual encaden...
4       ayer en cartagena él dar inicio a el versión n...
                              ...                        
1212    en el vida de todo empresa emergente llegar un...
1213    el espiral alcista de el precio continuar y ge...
1214    el grande derrota nacional ser experiencia tra...
1215    bbva haber alcanzar uno acuerdo de colaboració...
1216    casi entrar a el parte final de noviembre el é...
Name: news_lemma, Length: 1217, dtype: object

In [87]:

df['news_lemma'][3]

'con el dato de marzo el ipc interanual encadenar su decimoquinto tasa positivo consecutivo el inflación publicado por el ine él haber mantener igual respecto al avance del de marzo y él situar punto por encima del dato de febrero que ascender al ese punto de diferencia el mayor parte él colocar el grupo de el vivienda punto por el subida de el electricidad y el del transporte punto por el alza de el carburante también impulsar el ipc de marzo el aumento de el precio de el restauración y el servicio de alojamiento y al encarecimiento generalizado de el alimento especialmente del pescado y el marisco de el carne de el legumbr y hortaliza y de el leche el queso y el tener en cuenta el rebaja del impuesto especial sobre el electricidad y el variación sobre otro impuesto el ipc interanual alcanzar en marzo nueve décima más que el tasa general del así él reflejar el ipc a impuesto constante que el ine también publicar en el marco de este inflación subyacente sin alimento no elaborado ni pro

In [89]:
# Ahora haremos el modelo pero con la lemmatización

# Separamos los datos en variables de entrada y etiquetas
X= df['news_lemma']
y= df['Type']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)
vectorizer = CountVectorizer()
X_train_transformed= vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_transformed, y_train)

# Medimos el rendimiento dell modelo
y_pred = model.predict(X_test_transformed)

print(metrics.accuracy_score(y_test,y_pred))

# Nos dio algo mejor que el primer modelo y algo inferior al segundo modelo donde usamos stemming ( dependera de los textos) sin embargo la 
# lemmatización es un analisis más complejo porque les da algo de contexto a los tokens

0.7967213114754098


In [91]:
X_train_transformed
# La lemmatización como el Stemming reduce el nombre de dimensiones en comparación de la tokenización normal

<912x16100 sparse matrix of type '<class 'numpy.int64'>'
	with 181008 stored elements in Compressed Sparse Row format>